### PR TITLE
New weapon: Crossbow

### PR DESCRIPTION
**Pull request by Pkepowicz**
Added projectile based weapon - crossbow. Integrated it with stat system and used placeholder texture for projectile.
Couldn't find all necessary stats so used placeholders for now:
- Stat.DAMAGE - damage
- Stat.DAMAGERADIUS - size of projectile
- Stat.DODGE - number of fired projectiles after cooldown
- Stat.ATTACKSPEED - Cooldown between firing cycles
- Stat.DURATION - How many enemies bullet can pierce
Added example upgrades but they should be changed.

Additional note: noticed that when enemies are grouped crossbow bolts tend to skip dealing damage. This is caused by bolt's internal damage cooldown being too high, we can't really reduce it because it will deal damage multiple times during one collision. I suggest to change this internal cooldown to object specific cooldown in future as it doesn't affect game that much.

### CODE REVIEW

**Comment by Mlodko** [comment]
No consultation with the team or designers

**Comment by Mlodko** [comment]
Also no Trello task

**Comment by ddziechciarz** [comment]
I've asked for this weapon for AGH Games Hall so we can have some more variety when it comes to weapons. It will definitely be changed or removed later.

**Comment by Mlodko** [comment]
Keep it on a separate branch then, we don't want garbage on master

**Pull request merged**
