### PR TITLE
HealthBar, ExperienceBar, Drop system, Pickup system and level'up functionality

### PR DESCRIPTION
**Pull request by Bkasprzyk2077**
### health_bar
HelthBar has been added to hitbox component, so all enemies and player can display health. In order to hide HealthBar you have swich bool varialbe called **"Show Health Bar"** to **"false"**.

### progress_bar _(will be renamed to experience_bar in next patch)_
ExperienceBar is a canvas component added to world scene. It works witch **experience_manager** so it can display current player experience.

### experience_manager
ExperienceBar is a Node component added to world scene. It's responsible for managing player's experience _(storing current experience, leveling up when player reaches a certain number e.t.c)_.

### ItemDropComponent
ItemDropComponent is a Node added to enemy. You need to set **"Item Scene"** (item which will drop after enemy death), **Drop Percent** _(0 to 1 float number whch defines a percent of item to drop)_, **Hit Box Component** _(The component from which current health is retrieved)_ so it can work properly

### ExperienceCrystal
Experience Crystal is an item being spawned on enemy when he dies. When player collides with it, crystal disapears and gives certain amount of experience points to experience_manager. You can change amount of points, player gets.

...also
### GameEvents
GameEvents is a script which signals and functions responsible for emmiting them. GameEvents are set to **"auto load"** which means that they work as global variable. You can access them in any place in code and emit signal you want.

### CODE REVIEW

**Comment by Pkepowicz** [comment]
### Healthbar and progress bar
It's fine for now, in future we should work on graphic design of those bars. Also, I don't think it is necessary to have hp bars for all enemies.

### Experience manager and game events
looks legit, nothing to change.

### ItemDropComponent and ExperienceCrystal
I think we should have universal experienceCrystal that may change sprite depending on how much exp it holds. ItemDropComponent should inject exact experience value into experienceCrystal so it is easier to balance things out and it will save us making alot of similar scenes just to change one value. Addionaly collecting crystals lack any visual indication, we can do little animation where crystal slides into player from slightly larger collect radius similar to one showed on this tutorial [Link to YouTube with timestamp](https://youtu.be/LjV8rKWz9hY?si=WCkDi-EQkNdUCqK-&t=709)

**Review by ddziechciarz — APPROVED** [review]
git

**Comment by Mlodko** [comment]
[Add leveling functionality](https://trello.com/c/FRa9RRVF/17-add-leveling-functionality)

**Comment by Mlodko** [comment]
[Add pickup functionality](https://trello.com/c/QB8f7lV0/18-add-pickup-functionality)

**Comment by Mlodko** [comment]
[Add healthbar](https://trello.com/c/W2DIpG61/13-add-healthbar)

**Pull request merged**
